### ISSUE TITLE
Do you have any license on this project as a whole? Vim license?

### ISSUE THREAD

**Issue by yunboliu27** [kdeldycke/dotfiles#1]
Do you have any license on this project as a whole? Vim license?

**Comment by kdeldycke** [comment]
As you can attest by the [list of contributors](https://github.com/kdeldycke/dotfiles/graphs/contributors), I'm for the moment the sole author of all commits. So in theory I can apply any license I want.

The reality is more nuanced. This repository contain a couple of [third-party code and assets](https://github.com/kdeldycke/dotfiles#sources), each under their own license. Also, some commits are heavily inspired by other dotfiles repositories. Each time I borrow something, I try to credit the author and/or point to the source. You should be able to trace back my code from their origins. But that's a daunting task.

But you're right, I should explicit the current licensing state of this repository. I'm thinking of a BSD 2-clauses license. Is there any reason you suggested the Vim license?
